### ISSUE TITLE
Problems trying to access the Shinyapp

### ISSUE THREAD

**Issue by ghlopez** [pmartR/PMart_ShinyApp#1]
Hello, 
I have been trying to install and use pMart_ShinyApp and I am facing some issues and not being able to make it work. 
When I run the command shiny::runApp() to start the app I get this error message 

Listening on http://127.0.0.1:5367
Warning: Error in if: the condition has length > 1
  80: bsCollapse
  73: filter_UI [./tabs_UI/filter_tab.R#2]
  69: ui [/Users/glopez/Downloads/PMart_ShinyApp-master/ui.R#2]

Do you know what might be happening and how could I fix this? 
thanks in advance!

**Comment by clabornd** [comment]
Hi @ghlopez could you provide the printout of `sessionInfo()`?  I will try to replicate your error.

**Comment by clabornd** [comment]
Would also be useful if can you set `options("shiny.fullstacktrace" = TRUE)` and then trigger the error again and provide the output.
